#!/bin/sh

dwm_speed () {
  echo "["
  # cat ~/dwm/temp/speedtest-result | awk '{print $2}'
  # echo "ping"
  cat ~/scripts/arch-linux/temp/speedtest-result | awk '{print $5}'
  echo "down"
  cat ~/scripts/arch-linux/temp/speedtest-result | awk '{print $8}'
  echo "up ]"
}
dwm_sizes () {
  echo "["
  df -H --block-size M / | tail -1 | awk '{print $3}'
  echo "/ 50000M]"
}
dwm_packages () {
  echo "["
  cat ~/scripts/arch-linux/temp/package-info
  echo "]"
}
dwm_audio () {
  echo "[ audio:"
  pamixer --get-volume-human
  echo "]"
}
dwm_battery () {
  echo "["
  cat ~/scripts/arch-linux/temp/battery
  echo "]"
}
dwm_timedate () {
  date +"[ %a %d.%m.%Y %H:%M:%S ]"
}
#date +"[ %a %d.%m.%Y %I:%M:%S %p %Z ]" for  am/pm

while true
  do
    status=""
    status="$status"$(dwm_packages)""
    status="$status"$(dwm_audio)""
    status="$status"$(dwm_battery)""
    status="$status"$(dwm_timedate)""

    xsetroot -name "$(echo $status)"
    sleep 0.5
done
