#!/bin/sh

package_count=$(pacman -Q 2> /dev/null | wc -l)
updates_arch=$(checkupdates 2> /dev/null | wc -l)
updates_aur=$(yay -Qua --devel 2> /dev/null | wc -l)
updates=$(($updates_arch + $updates_aur))
if [ "$updates" -ge 2 ]; then
  echo "$package_count packages $updates updates" > ~/scripts/arch-linux/temp/package-info
elif [ "$updates" -eq 1 ]; then
  echo "$package_count packages 1 update" > ~/scripts/arch-linux/temp/package-info
elif [ "$updates" -eq 0 ]; then
  echo "$package_count packages" > ~/scripts/arch-linux/temp/package-info
fi
