"          _
"   _   __(_)___ ___  __________
"  | | / / / __ `__ \/ ___/ ___/
" _| |/ / / / / / / / /  / /__
"(_)___/_/_/ /_/ /_/_/   \___/

" plugin installs
source $HOME/.vim/plugin-config/master-install.vim
" plugin config
source $HOME/.vim/plugin-config/gitgutter.vim
source $HOME/.vim/plugin-config/autoformat.vim
source $HOME/.vim/plugin-config/markdown-preview.vim
source $HOME/.vim/plugin-config/latex-live-preview.vim

" switch between header and source files
source $HOME/.vim/a.vim

" custom commands
command! PU PlugUpdate | PlugUpgrade
command! Vterm vert term

" keymaps
source $HOME/.vim/keymaps.vim

let skip_defaults_vim=1
set viminfo+=n~/.local/share/viminfo
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
endif
set encoding=utf-8
set fileencoding=utf-8
set number relativenumber
autocmd InsertEnter * :set norelativenumber
autocmd InsertLeave * :set relativenumber
set mouse=a
set mousehide
set cursorline
set wrap
autocmd BufRead,BufNewFile *.pdf,*.txt,*.md,*.tex setlocal wrap linebreak nolist
autocmd BufRead,BufNewFile *.txt,*.md,*.tex setlocal spell
autocmd BufRead,BufNewFile CMakeLists.txt setlocal nospell
autocmd BufRead,BufNewFile *.pdf setlocal readonly
set spellcapcheck=0
set spelllang=en
set spellfile=$HOME/sync/vim/spell/en.utf-8.add
syntax on
set updatetime=100 " update things every 100ms (helps git gutter)
autocmd BufRead,BufNewFile,BufEnter *.tex setlocal updatetime=5000 " higher update time for latex files improves preview
set nobackup noswapfile
set history=100
set backspace=indent,eol,start " more powerful backspacing
set tabstop=2
set shiftwidth=2
set expandtab
set undolevels=1000
set hidden
set clipboard=unnamed
set ai si " autoindenting and smartindenting
set hlsearch
set ignorecase smartcase
set autoread " autoreload file
set noeb vb t_vb= " no bell

" splits
set splitbelow
set splitright
"set fillchars+=vert:\█ " trailing space works better with no termguicolors
set fillchars+=vert:\ 

" indicators
set list listchars=tab:>·,trail:~,extends:>,precedes:<,space:·

" file explorer
let g:netrw_banner = 0
let g:netrw_winsize = 15

" cursor in insert mode
if exists('$TMUX')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\e[5 q\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\e[2 q\<Esc>\\"
elseif $TERM_PROGRAM =~ "iTerm"
  let &t_SI = "\<Esc>]50;CursorShape=1\x7" " vertical bar in insert mode
  let &t_EI = "\<Esc>]50;CursorShape=0\x7" " block in normal mode
else
  let &t_SI = "\e[5 q"
  let &t_EI = "\e[2 q"
endif

set timeout ttimeout " separate mapping and keycode timeouts
set timeoutlen=500   " mapping timeout 500ms  (adjust for preference)
set ttimeoutlen=20   " keycode timeout 20ms

function TerminalManager()
  setlocal norelativenumber
  setlocal nonumber
  silent! normal i
endfunction

augroup terminalmanagement
  autocmd TerminalOpen call TerminalManager()
  autocmd BufWinEnter,FocusGained * if &buftype == 'terminal' | call TerminalManager() | endif 
augroup END

let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'mode_map': {
        \ 'n' : 'VIM'
        \ },
        \ 'component_function': {
          \'gitbranch': 'gitbranch#name'
          \ }
          \ }

let g:lightline.active = {
      \ 'left': [ [ 'mode', 'paste' ],
      \           [ 'readonly', 'filename', 'modified', 'gitbranch' ] ],
      \ 'right': [ [ 'lineinfo' ],
      \            [ 'percent'  ],
      \            [ 'fileformat'] ]
      \ }

let g:lightline.tabline = {
      \ 'left': [ [ 'tabs' ] ],
      \ 'right': [ [ 'buffer' ] ]
      \ }

" for lightline and statusline
set noshowmode showcmd
set ruler
set laststatus=2
set showtabline=2
set guioptions-=e

" color options (best to be put last in the vimrc)
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set background=dark
set notermguicolors
colorscheme peachpuff
highlight Comment guibg=green ctermfg=green
highlight Visual guibg=blue ctermfg=blue
highlight Search guibg=blue ctermbg=blue term=underline
highlight IncSearch guibg=blue ctermbg=blue term=underline
highlight clear SignColumn
