#!/bin/sh

xmodmap -e "add mod4 = Print"

dwmblocks &
#(sleep 60 && speedtest10m) &
#(while true; do random-wallpaper; sleep 3600; done) &
random-wallpaper &
#redshift -l manual &
(sleep 0.1 && picom) &
(sleep 0.1 && dunst) &
