#!/bin/sh

# Shows the current moon phase.

moonfile="${XDG_DATA_HOME:-$HOME/.local/share}/moonphase"

[ "$(stat -c %y "$moonfile" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] || { curl -sf "wttr.in/?format=%m" > "$moonfile" || exit 1 ;}

icon="$(cat "$moonfile")"

case "$icon" in
	🌑) name="New" ; nficon="";;
	🌒) name="Waxing Crescent" ; nficon="";;
	🌓) name="First Quarter" ; nficon="";;
	🌔) name="Waxing Gibbous" ; nficon="";;
	🌕) name="Full" ; nficon="";;
	🌖) name="Waning Gibbous" ; nficon="";;
	🌗) name="Last Quarter" ; nficon="";;
	🌘) name="Waning Crescent" ; nficon="";;
	*) exit 1 ;;
esac

echo "${nficon-?}"
